"""Add SchemaValidationLog table

Revision ID: 14e5599e174d
Revises: 407162db9ed3
Create Date: 2025-11-12 07:39:10.968395+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e5599e174d'
down_revision = '407162db9ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###