"""Add SchemaValidationLog table

Revision ID: 407162db9ed3
Revises: d467ebdfd2ec
Create Date: 2025-11-12 07:28:36.168927+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407162db9ed3'
down_revision = '8f39452e56cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###