"""add is_active to schemas table

Revision ID: 54cd24a12d09
Revises: f5cd1fa3c00e
Create Date: 2025-11-13 08:31:45.201414+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cd24a12d09'
down_revision = '518cd8c69c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemas', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemas', 'is_active')
    # ### end Alembic commands ###