"""Implement secure API key hashing

Revision ID: 97db48d397e0
Revises: 14e5599e174d
Create Date: 2025-11-12 08:37:02.024299+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97db48d397e0'
down_revision = '14e5599e174d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###