"""Add schema_id to schema_validation_logs

Revision ID: a168c9193ded
Revises: 54cd24a12d09
Create Date: 2025-11-13 08:47:19.210093+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a168c9193ded'
down_revision = '54cd24a12d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_validation_logs', sa.Column('schema_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_schema_validation_logs_schema_id'), 'schema_validation_logs', ['schema_id'], unique=False)
    op.create_foreign_key(None, 'schema_validation_logs', 'schemas', ['schema_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schema_validation_logs', type_='foreignkey')
    op.drop_index(op.f('ix_schema_validation_logs_schema_id'), table_name='schema_validation_logs')
    op.drop_column('schema_validation_logs', 'schema_id')
    # ### end Alembic commands ###