"""Add reconciliation_reports table

Revision ID: c29611304459
Revises: a168c9193ded
Create Date: 2025-11-13 20:23:53.543527+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29611304459'
down_revision = 'a168c9193ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('internal_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('external_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('variance_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('variance_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_reports_id'), 'reconciliation_reports', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_organization_id'), 'reconciliation_reports', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_reports_organization_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_id'), table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    # ### end Alembic commands ###