"""Add validation_logs table

Revision ID: d467ebdfd2ec
Revises: 8f39452e56cf
Create Date: 2025-11-11 23:43:19.423178+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd467ebdfd2ec'
down_revision = '8f39452e56cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###